#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64GB
#SBATCH --time=1:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --account=ajoshi_27

eval "$(conda shell.bash hook)"

conda activate few-shot
cd /scratch1/hedongzh/brainseg

module purge
module load nvidia-hpc-sdk
module load gcc/8.3.0

python /scratch1/hedongzh/brainseg/test_brain/demo.py --loss='BCE' --beta='0.0001' --warmup=2 --suffix=weighted_BCE
